services:
  - type: web
    name: bonnie-telegram-bot
    env: python
    plan: starter
    buildCommand: |
      pip install --upgrade pip &&
      pip install --no-cache-dir -r requirements.txt
    startCommand: python bonnie_bot.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: ENVIRONMENT
        value: production
      - key: LOG_LEVEL
        value: INFO
      - key: PYTHONUNBUFFERED
        value: "1"
    healthCheckPath: /health
    autoDeploy: true
    region: oregon
    scaling:
      minInstances: 1
      maxInstances: 3