# 🚀 BONNIE ULTIMATE AI GIRLFRIEND SYSTEM - Render Deployment Configuration
# This file defines all services needed for production deployment on Render

services:
  - type: web
    name: bonnie-ai-production
    env: node
    region: oregon
    plan: starter
    buildCommand: cd backend && npm install --production
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: AI_MODEL
        value: openai/gpt-4o-mini
      - key: LOG_LEVEL
        value: info
      - key: HEALTH_CHECK_ENABLED
        value: true
      - key: ENABLE_HELMET
        value: true
      - key: ENABLE_COMPRESSION
        value: true
      - key: RATE_LIMIT_FREE
        value: 20
      - key: RATE_LIMIT_PREMIUM
        value: 60
      - key: RATE_LIMIT_VIP
        value: 120
      - key: CIRCUIT_BREAKER_THRESHOLD
        value: 5
      - key: CIRCUIT_BREAKER_TIMEOUT
        value: 60000
      - key: ENABLE_CONTENT_MODERATION
        value: true
      - key: MIN_RESPONSE_DELAY
        value: 400
      - key: MAX_RESPONSE_DELAY
        value: 4000
    healthCheckPath: /health
    autoDeploy: true
    preDeployCommand: echo "🚀 Deploying Bonnie AI Production v24.0"
    
  # Optional Redis add-on for enhanced performance
  # Uncomment to enable advanced caching
  # - type: redis
  #   name: bonnie-redis
  #   plan: starter
  #   maxmemoryPolicy: allkeys-lru

  # Static Frontend Service (Optional)
  - type: static
    name: bonnie-ai-frontend
    buildCommand: npm run build
    staticPublishPath: ./dist
    repo: https://github.com/trainmygirl/bonnie-ai-frontend.git
    branch: main
    
    # Custom Headers
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=31536000, immutable
      - path: /index.html
        name: Cache-Control
        value: public, max-age=0, must-revalidate
    
    # Routes Configuration
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  # Background Worker Service (Optional)
  - type: worker
    name: bonnie-ai-worker
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: node workers/background-tasks.js
    repo: https://github.com/trainmygirl/bonnie-ai-system.git
    branch: main
    
    envVars:
      - key: NODE_ENV
        value: production
      - key: WORKER_TYPE
        value: background_tasks
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false

# Database Configuration (External - Supabase)
databases: []

# Redis Configuration (Optional - for caching)
# Note: You can add Redis from Render's add-ons or use external service
redis: []

# Cron Jobs for Maintenance
crons:
  - name: daily-cleanup
    schedule: "0 2 * * *" # Every day at 2 AM
    command: node scripts/daily-cleanup.js
    
  - name: weekly-analytics
    schedule: "0 3 * * 0" # Every Sunday at 3 AM
    command: node scripts/weekly-analytics.js
    
  - name: health-check
    schedule: "*/15 * * * *" # Every 15 minutes
    command: curl -f $RENDER_EXTERNAL_URL/health

# Environment Groups (Optional - for shared env vars)
envGroups: []

# Alerts Configuration
alerts:
  - name: high-error-rate
    rules:
      - field: error_rate
        op: ">"
        value: 0.05 # 5% error rate
        duration: 300 # 5 minutes
    notifications:
      - type: email
        target: admin@trainmygirl.com

  - name: high-response-time
    rules:
      - field: response_time_p95
        op: ">"
        value: 2000 # 2 seconds
        duration: 300
    notifications:
      - type: slack
        target: "#alerts"

  - name: low-memory
    rules:
      - field: memory_usage
        op: ">"
        value: 0.85 # 85% memory usage
        duration: 180 # 3 minutes
    notifications:
      - type: email
        target: admin@trainmygirl.com