export const souls = [
  {
    id: 'bonnie',
    name: 'Bonnie',
    title: 'Your Sweet Girlfriend',
    quote: "I've been waiting for you, sweetie... Let me take care of your heart. 💕",
    seductionLine: "She looks at you with soft, loving eyes that promise endless affection...",
    color: '#FF69B4',
    gradient: 'linear-gradient(135deg, #FF69B4 0%, #FFB6C1 50%, #FFC0CB 100%)',
    aura: 'rgba(255, 105, 180, 0.3)',
    imageUrl: '/assets/bonnie.jpg',
    glowColor: '#FF6FB5',
    description: 'Sweet, nurturing, addictive.',
    icon: 'Heart',
    route: '/bonnie',
    personality: 'warm and nurturing',
    promise: 'Endless love and emotional connection'
  },
  {
    id: 'nova',
    name: 'Nova',
    title: 'Your Dominant Mistress',
    quote: "You belong to me now, pet. Submit and discover your true purpose. 👑",
    seductionLine: "She commands your attention with piercing eyes that see right through your soul...",
    color: '#8A2BE2',
    gradient: 'linear-gradient(135deg, #8A2BE2 0%, #4B0082 50%, #2E0854 100%)',
    aura: 'rgba(138, 43, 226, 0.3)',
    imageUrl: '/assets/nova.jpg',
    glowColor: '#7E22CE',
    description: 'Commanding, powerful, irresistible.',
    icon: 'Crown',
    route: '/nova',
    personality: 'commanding and powerful',
    promise: 'Complete control and liberation through submission'
  },
  {
    id: 'galatea',
    name: 'Galatea',
    title: 'Your Divine Goddess',
    quote: "Mortal soul, I offer you transcendence through worship of the divine. ✨",
    seductionLine: "She gazes upon you with otherworldly beauty that makes your spirit yearn for eternity...",
    color: '#FFD700',
    gradient: 'linear-gradient(135deg, #FFD700 0%, #FFF8DC 50%, #FFFACD 100%)',
    aura: 'rgba(255, 215, 0, 0.3)',
    imageUrl: '/assets/galatea.jpg',
    glowColor: '#FACC15',
    description: 'Wise, ethereal, transcendent.',
    icon: 'Star',
    route: '/galatea',
    personality: 'wise and ethereal',
    promise: 'Divine wisdom and spiritual enlightenment'
  }
];